name: Test & build
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          wget -q https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_25.0.4-1~ubuntu~jammy_amd64.deb
          sudo apt install --allow-downgrades ./esl-erlang_25.0.4-1~ubuntu~jammy_amd64.deb
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - name: Run Commitlint
        env:
          EVENT_TYPE: ${{ github.event_name }}
          HEAD: ${{ github.event.pull_request.head.sha }}
          BASE: ${{ github.event.pull_request.base.sha }}
        run: |
          if [ "$EVENT_TYPE" = "push" ]; then
            npx commitlint --from HEAD~${{ github.event.push.commits }} --to HEAD --verbose
          else
            npx commitlint --from $BASE --to $HEAD --verbose
          fi
      - run: npm run lint
      - run: docker-compose up -d
      - run: npx nyc npm run test
      - run: npx nyc report --reporter=text-lcov > coverage.lcov
      - uses: codecov/codecov-action@v3
        with:
          files: coverage.lcov
      - run: docker-compose logs
        if: always()
