name: Test & build
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt install --no-install-recommends erlang
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - name: Run Commitlint
        env:
          EVENT_TYPE: ${{ github.event_name }}
          HEAD: ${{ github.event.pull_request.head.sha }}
          BASE: ${{ github.event.pull_request.base.sha }}
        run: |
          if [ "$EVENT_TYPE" = "push" ]; then
            npx commitlint --from HEAD~${{ github.event.push.commits }} --to HEAD --verbose
          else
            npx commitlint --from $BASE --to $HEAD --verbose
          fi
      - run: npm run lint
      - run: docker compose up -d
      - run: npx nyc npm run test
      - run: npx nyc report --reporter=text-lcov > coverage.lcov
      - uses: codecov/codecov-action@v4
        with:
          files: coverage.lcov
      - run: docker compose logs
        if: always()
